version: '3.8'

services:
  frontend:
    image: frontend
    container_name: Frontend
    ports:
      - 3000:80
    depends_on:
      - backend

  backend:
    image: backend
    container_name: Backend
    environment:
      - DB=mongodb://database:27017/mydatabase4
    ports:
      - 5000:5000
    depends_on:
      - database

  database:
    image: mongo
    container_name: Database
    ports:
      - 27017:27017
      
